# exercise 1 creating series from array

In [1]:
import pandas as pd 
import numpy as np

In [3]:
info=np.array(['p','a','n','d','a','s'])


In [5]:
a=pd.Series(info)
print(a)

0    p
1    a
2    n
3    d
4    a
5    s
dtype: object


In [6]:
#Exercise `1 dataframe

In [8]:
import pandas as pd 
x=['Python','Pandas']
df=pd.DataFrame(x)
print(df)

        0
0  Python
1  Pandas


In [9]:
#Exercise 1 pandas series.map

In [16]:
#example1
import pandas as pd
import numpy as np
a=pd.Series(['Java','C','C++',np.nan])
a.map({'Java':'Core'})


0    Core
1     NaN
2     NaN
3     NaN
dtype: object

In [14]:
#example2
import pandas as pd
import numpy as np
a=pd.Series(['Java','C','C++',np.nan])
a.map({'Java':'Core'})
a.map('i like {}'.format,na_action='ignore')

0    i like Java
1       i like C
2     i like C++
3            NaN
dtype: object

In [18]:
#Parameters(name)Example 1
s = pd.Series(["a","b","c"],name="vals")
s.to_frame()

vals
0    a
1    b
2    c

In [24]:
#example2
import pandas as pd 
import matplotlib.pyplot as plt
emp = ['Parker','John','Smith','william']
id=[102,107,109,114]
emp_series=pd.Series(emp)
id_series=pd.Series(id)
frame={'Emp':emp_series,'ID':id_series}
result=pd.DataFrame(frame)
print(result)

       Emp   ID
0   Parker  102
1     John  107
2    Smith  109
3  william  114


# Exercise 2


In [27]:
#creating an empty dataframe
import pandas as pd
df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [28]:
#creating dataframe using list
import pandas as pd 
x=["Python","Pandas"]
df=pd.DataFrame(x)
print(df)

        0
0  Python
1  Pandas


In [30]:
#creating dataframe from dict of ndarray/list
import pandas as pd
info={'ID':[102,107,109],'Department':['B.Tech','B.Sc','M.tech']}
df=pd.DataFrame(info)
print(df)

    ID Department
0  102     B.Tech
1  107       B.Sc
2  109     M.tech


In [34]:
#Creating a dataframe from a dict of series
import pandas as pd
info={'one':pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f']),'two':pd.Series([1,2,3,4,5,6,7,8],index=['a','b','c','d','e','f','g','h'])}
d1=pd.DataFrame(info)
print(d1)

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  4.0    4
e  5.0    5
f  6.0    6
g  NaN    7
h  NaN    8


In [35]:
#column selection
import pandas as pd
info={'one':pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f']),'two':pd.Series([1,2,3,4,5,6,7,8],index=['a','b','c','d','e','f','g','h'])}
d1=pd.DataFrame(info)
print(d1['one'])

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    6.0
g    NaN
h    NaN
Name: one, dtype: float64


In [39]:
#column addition
import pandas as pd
info={'one':pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f']),'two':pd.Series([1,2,3,4,5,6,7,8],index=['a','b','c','d','e','f','g','h'])}
d1=pd.DataFrame(info)
print("Add new column by passing series")
d1["three"]=pd.Series([1,2,3],index=['a','b','c'])
print(d1)
print("Add new columns using existing Dataframe columns ")
d1['four']=d1['one']+d1['three']
print(d1)

Add new column by passing series
   one  two  three
a  1.0    1    1.0
b  2.0    2    2.0
c  3.0    3    3.0
d  4.0    4    NaN
e  5.0    5    NaN
f  6.0    6    NaN
g  NaN    7    NaN
h  NaN    8    NaN
Add new columns using existing Dataframe columns 
   one  two  three  four
a  1.0    1    1.0   2.0
b  2.0    2    2.0   4.0
c  3.0    3    3.0   6.0
d  4.0    4    NaN   NaN
e  5.0    5    NaN   NaN
f  6.0    6    NaN   NaN
g  NaN    7    NaN   NaN
h  NaN    8    NaN   NaN


In [41]:
#column deletion
import pandas as pd
info={'one':pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f']),'two':pd.Series([1,2,3,4,5,6,7,8],index=['a','b','c','d','e','f','g','h'])}
d1=pd.DataFrame(info)
print("The DataFrame: ")
print(d1)
#using del function
print("deletion of first column")
del d1['one']
print(d1)
#using pop functions
print("Delete the another column: ") 
d1.pop('two')
print(d1)

The DataFrame: 
   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  4.0    4
e  5.0    5
f  6.0    6
g  NaN    7
h  NaN    8
deletion of first column
   two
a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
Delete the another column: 
Empty DataFrame
Columns: []
Index: [a, b, c, d, e, f, g, h]


In [43]:
#row selection 
#selection by Labels
import pandas as pd
info={'one':pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f']),'two':pd.Series([1,2,3,4,5,6,7,8],index=['a','b','c','d','e','f','g','h'])}
d1=pd.DataFrame(info)
print(d1.loc['b'])

one    2.0
two    2.0
Name: b, dtype: float64


In [44]:
#selection by integer location
import pandas as pd
info={'one':pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f']),'two':pd.Series([1,2,3,4,5,6,7,8],index=['a','b','c','d','e','f','g','h'])}
d1=pd.DataFrame(info)
print(d1.iloc[3])

one    4.0
two    4.0
Name: d, dtype: float64


In [45]:
#slice row
import pandas as pd
info={'one':pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f']),'two':pd.Series([1,2,3,4,5,6,7,8],index=['a','b','c','d','e','f','g','h'])}
d1=pd.DataFrame(info)
print(d1[2:5])

   one  two
c  3.0    3
d  4.0    4
e  5.0    5


In [53]:
#Addition of rows
import pandas as pd
q = pd.DataFrame([[7,8],[9,10]],columns = ['x','y'])
q2 = pd.DataFrame([[11,12],[13,14]],columns = ['x','y'])
q = q.append(q2)
print(q)

AttributeError: 'DataFrame' object has no attribute 'append'

# exercise 7


In [6]:
import array 
arr=array.array('I',[2,4,6,8,10,12])
print("Newly Created Array:",end=" ")
for i in range(0,5):
    print(arr[i], end =" ")
    print("\r")

Newly Created Array: 2 
4 
6 
8 
10 


In [9]:
import pandas as pd
dict={'name':['Ayush','armaan','harsh','meemansa']}
df=pd.DataFrame(dict,index=['row1','row2','row3','row4'])
print(df)

          name
row1     Ayush
row2    armaan
row3     harsh
row4  meemansa


In [11]:
import numpy as np
arr = np.arange(16)#by default 0-15 range banata h 
print("The Original array is :\n",arr)
#shape array with 2 rows and 8 columnns
arr = np.arange(16).reshape(2,8)
print("\nreshapedarry:\n",arr)
#shape array withgh 2 rows and 8 columns
arr = np.arange(16).reshape(8,2)
print("\nreshapedarray:\n",arr)

The Original array is :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

reshapedarry:
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]

reshapedarray:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


# Exercise 8

In [14]:

import numpy as np
a = np.array([1,2,3])
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(3,)


In [15]:
print(a[0],a[1],a[2])
a[0]=5
print(a)
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0],b[0,1],b[1,0])


1 2 3
[5 2 3]
(2, 3)
1 2 4


In [19]:
#nstructor exercise overview
import numpy as  np
a = np.zeros((2,2))#zeros is used for missing values
print(a)

b= np.ones((1,2))
print(b)
c=np.full((2,2),7)#to create a 2*2 matrix
print(c)
d=np.eye((2))#to make a 2*2 identity matrix
print(d)
e=np.random.random((2,2))
print(e)


[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.54051921 0.51474227]
 [0.49305735 0.28570073]]


In [20]:
#Array indexing
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,110,11,12]])
b = a[:2,1:3]

print(a[0,1])
b[0,0]=77
a[0,1]
print(a[0,1])

2
77


In [21]:
#Array Slicing
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
row_r1 = a[1,:]
row_r2 = a[1:2,:]
print(row_r1,row_r1.shape)
print(row_r2,row_r2.shape)
col_r1 = a[:,1]
col_r2 = a[:,1:2]
print(col_r1,col_r1.shape)
print(col_r2,col_r2.shape)


[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [23]:
#integer array indexng
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2],[0,1,0]])
print(np.array([a[0,0],a[1,1],a[2,0]]))
print([a[0,0],a[1,1]])
print(np.array([a[0,1],a[0,1]]))


[1 4 5]
[1 4 5]
[1, 4]
[2 2]


In [25]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
b= np.array([0,2,0,1])
a[np.arange(4),b]+= 10
print(a)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [29]:
#Boolean array indexing
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
bool_idx = (a>2)
print(bool_idx)
print(a[bool_idx])
print(a[a>2])
    

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [31]:
#Datatypes
import numpy as np
x = np.array([1,2])
print(x.dtype)
x = np.array([1.0,2.0])      
x = np.array([1,2],dtype=np.int64) 
print(x.dtype)

int32
int64


In [3]:
#Array  math
import numpy as np
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))
print(np.sqrt(x))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [4]:
import numpy as np
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
#ineer product of vector 
print(v.dot(w))
print(np.dot(v,w))
#matrix /vector product;both produce the rank1 [29,67]
print(x.dot(v))
print(np.dot(x,v))
#Matrix/Matrix product;both produce the rank 2[[19,22][43,50]]
print(x.dot(y))
print(np.dot(x,y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [5]:
import numpy as np 
x = np.array([[1,2],[3,4]])
print(np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

10
[4 6]
[3 7]


In [7]:
import numpy as np
x = np.array([[1,2],[3,4]])
print(x)
print(x.T)
v=np.array([1,2,3])
print(v)
print(v.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]
